### ISSUE TITLE
static folder missing?

### ISSUE THREAD

**Issue by mhingston** [etesync/server-skeleton#11]
Hi,

Thanks for the project. There don't seem to be any static assets in the repo?

**Comment by tasn** [comment]
Hey,

Nothing is missing. Take a look at the readme, you need to run "collectstatic" to generate the static folder.

**Comment by adeschamps** [comment]
Can this be reopened? This isn't mentioned in the README.

**Comment by daftaupe** [comment]
Hello, @adeschamps check https://github.com/etesync/server/wiki/Production-setup-using-uWSGI-and-Nginx#setup-nginx please.

**Comment by adeschamps** [comment]
Ah, I see it now. I missed that part of the wiki. Thanks!

**Comment by ljani** [comment]
Now that uWSGI support is deprecated, maybe it should be mentioned elsewhere as well? At least I skipped reading that page because of the first paragraph:

> uWSGI is no longer supported by Etebase. This page is only here for legacy reasons.
