### ISSUE TITLE
Bad Request (400) on self hosted eteSync server

### ISSUE THREAD

**Issue by romjean** [etesync/server-skeleton#18]
Hi,
I'm facing some issues making eteSync server working on my VPS. Installation worked well.
Here my settings:
Apache virtual host (ssl):
```<IfModule mod_ssl.c>
<VirtualHost *:443>

ServerAdmin xxx@xxx.xx 
ServerName xxx.xxxxxxx.xx 

<Location "/">
ProxyPass        http://localhost:8000/ retry=0
ProxyPassReverse http://localhost:8000/
RequestHeader    set X-Script-Name /
</Location>

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem

</VirtualHost>
</IfModule>
```

etesync-server.ini:
```[global]
secret_file = secret.txt
debug = False

[allowed_hosts]
allowed_hosts = localhost

[database]
engine = django.db.backends.sqlite3
name = db.sqlite3
```

Then, when typing the command `./manage.py runserver localhost:8000` everything looks fine, but when I try to access to the web page xxx.xxxxxxxx.xx (the ServerName set up in my Apache's VirtualHost), I have a lovely "Bad Request (400)" error...
I can however access to the "admin" part of it through the http://localhost:8000 address directly on my VPS (but with no css loaded...)

Any idea of where the mistake is ?
Thanks a lot !

Romain

**Comment by daftaupe** [comment]
Hello,

    allowed_hosts = localhost

should have the value

    allowed_hosts = xxx.xxx.xxx.xxx (your domain name)

Regards,

**Comment by romjean** [comment]
Thanks @daftaupe ,
However, after changing the `allowed_host1 = xx.xxxxxx.xx` (my domain), I still have the same error.
Romain

> Hello,
> 
> ```
> allowed_hosts = localhost
> ```
> 
> should have the value
> 
> ```
> allowed_host1 = xxx.xxx.xxx.xxx (your domain name)
> ```
> 
> You can have more in that fashion (if you have several domains)
> 
> ```
> allowed_host1 = xxx.xxx.xxx.xxx
> allowed_host2 = yyy.yyy.yyy.yyy
> ```
> 
> Regards,

**Comment by tasn** [comment]
Could you please try adding `allowed_host2 = *` and see if that makes it work? If so, that means it's indeed a problem with the allowed_host.

Additionally, could you potentially also turn debugging on so we get more information about what's going on?

**Comment by romjean** [comment]
I've added `allowed_host2 = *`, turned on the debug mode and here what it comes:

<img width="615" alt="error" src="https://user-images.githubusercontent.com/15798122/59038907-11ef7380-8874-11e9-8a08-0fca7980bc5b.png">

**Comment by tasn** [comment]
Yeah that means it works (try the `/admin` path which is a valid one). So the issue is indeed a problem with the allowed_host being wrong. What's the error you're getting with debug on and without the allowed_host2 line you added?

**Comment by daftaupe** [comment]
Can you post your reverse-proxy configuration also ? It might be not passing the right info to the backend, including the Host variable.

**Comment by romjean** [comment]
Hi,
I removed the `allowed_host2 = *` line from the .ini file and set the appropriate host.
Now my Apache VirtualHost settings look like this:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>

ServerAdmin xxx@xxx.xxx
ServerName xxxx.xxxxxxx.xx

<Location "/">
    ProxyPass http://localhost:8000/
    ProxyPassReverse http://localhost:8000/
    ProxyPreserveHost On
</Location>

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
</VirtualHost>
</IfModule>
```
With debug mode activated, the homepage looks like this:
<img width="620" alt="homepage" src="https://user-images.githubusercontent.com/15798122/59087714-c7b6d280-8905-11e9-9373-16914469d893.png">

And the admin page works well:
<img width="936" alt="admin" src="https://user-images.githubusercontent.com/15798122/59087773-f92f9e00-8905-11e9-9cef-09089bbbaa43.png">

I'm wondering if my wsgi parameters are ok or not.
Here what's in my apache2.conf file (in /etc/apache2/):
```
WSGIScriptAlias xxx.xxxxxx.fr /root/server-skeleton/etesync_server/wsgi.py
WSGIPythonPath /root/server-skeleton/etesync_server

WSGIProcessGroup %{GLOBAL}
WSGIApplicationGroup %{GLOBAL}

<Location "/secret">
    AuthType Basic
    AuthName "Top Secret"
    Require valid-user
    AuthBasicProvider wsgi
    WSGIAuthUserScript /root/server-skeleton/etesync_server/wsgi.py
</Location>
```

**Comment by tasn** [comment]
Please update the server skeleton code. I added an index page so it's more obvious things work when they do.

Anyhow, based on your latest screenshot it looks like things work. Have you tried using it?

**Comment by romjean** [comment]
Yes now I can see the "It Works !" page and the admin page still works. Thanks !
However, I can't log in from the Android app even having selected the "show advanced settings" box and typed the web address of my personal server. The Android app says "Couldn't authenticate, Have you registered ?" If I try to sign up in the Android app, I can see the normal signing up page asking to chose a plan, as if I was using the normal etesync service.
Help !

**Comment by romjean** [comment]
OK I tried with my username instead of the email address and it works !!!!!
Thanks a lot for your help. Closing down.
Rom

**Comment by tasn** [comment]
Yay. :)
