### ISSUE TITLE
Authentication credentials were not provided.

### ISSUE THREAD

**Issue by mzch** [etesync/server-skeleton#19]
I added super user using manage.ph createsuperuser but I can't login Etesync server via Etesync Web client because of an error as below. I can login admin panel directly.
What's the matter?

There is no Apache error log about this.

```
Something went wrong!
Authentication credentials were not provided.
Stack trace:
Error: Authentication credentials were not provided.
    at t (https://www.noncal.com/static/js/main.15b3646a.chunk.js:1:5629)
    at new t (https://www.noncal.com/static/js/main.15b3646a.chunk.js:1:5793)
    at https://www.noncal.com/static/js/main.15b3646a.chunk.js:1:12203
```

**Comment by tasn** [comment]
This authentication credentials not provider error, when did you get it? Upon trying to log into the web client? Could you open the browser's dev tools and check what's going on in the network tab?

It sounds like Apache isn't passing the Authorization header, could you please check that? Potentially related: #18 or probably #6 (both were a misconfigured Apache).

**Comment by mzch** [comment]
Thanks, @tasn 
Adding WSGIPassAuthorization resolved this issue.
