### ISSUE TITLE
Config file.

### ISSUE THREAD

**Issue by HybridGlucose** [etesync/server-skeleton#20]
In old version I used to setting `ALLOWED_HOSTS` in `setting.py` and `README.md` also say that choose one to config.
But after I update server-skeketon it can't be access.
If I don't config `etesync-server.ini` the service can't work get this error:
`CommandError: You must set settings.ALLOWED_HOSTS if DEBUG is False.`.

**Comment by daftaupe** [comment]
Hello @HybridGlucose,

you should provide the content of both settings.py and etesync-server.ini regarding ALLOWED_HOSTS and the [allowed_hosts] section. That would make it easier for us to help you.

etesync-server.ini shouldn't be taken into account if the [allowed_hosts] is left as shipped with the git repo, that is with a commented entry. Can you confirm you didn't touch it ?

You can try removing the file itself, in that case you will be sure only settings.py will be taken into account.

Regards,

**Comment by tasn** [comment]
As @daftaupe said, if you configure from Python and not the .ini, everything should just work. If it's not the case then there's a regression that should be addressed.

**Comment by HybridGlucose** [comment]
I got it.
Because I update server-skeleton just like `README.md#Updating` said, so I have two file `setting.py` and `etesync-server.ini`.
If I delete or rename `etesync-server.ini` all is fine.
Thanks a lot.

**Comment by tasn** [comment]
Oops, I just see what the issue is, and it's as you described. I'm reopening this ticket and either @daftaupe or I will fix it asap. :)

Thanks for reporting!
