### ISSUE TITLE
UNAUTHORIZED auth token

### ISSUE THREAD

**Issue by jrvarma** [etesync/server-skeleton#6]
I have installed the server as instructed and the application is being served over https by Apache. I am able to log in as superuser and create/delete users and do other admin tasks. However all the clients (Android, web and python) are failing authentication with the error `UNAUTHORIZED auth token`. Using the [python interface](https://github.com/etesync/pyetesync), I can verify that the line

     authToken = api.Authenticator(remoteUrl).get_auth_token(email, servicePassword)

returns the correct token that can be viewed in the admin panel. The line

    etesync = api.EteSync(email, authToken, remote=remoteUrl)

does not report any error. But the line

    etesync.sync()

fails with `UNAUTHORIZED auth token`

**Comment by tasn** [comment]
I would suspect apache is not forwarding the auth token correctly. Easiest
way to verify is to use etesync web, open the developer tools, and check
the network requests to see if it's correctly passed in the headers.

**Comment by jrvarma** [comment]
This is what I get when I do that from a Chromium browser. I have masked the token (it matches what I can see in the admin tab).

General
Request URL: https://etes.jrvarma.in/api/v1/user/jrvarma@jrvarma.in/
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 208.97.140.110:443
Referrer Policy: no-referrer-when-downgrade

Response Headers
Access-Control-Allow-Origin: *
Allow: GET, POST, PUT, DELETE
Connection: Keep-Alive
Content-Length: 58
Content-Type: application/json
Date: Sun, 21 Oct 2018 15:25:47 GMT
Keep-Alive: timeout=5, max=98
Server: Apache/2.4.29 (Ubuntu)
Vary: Accept,Cookie
WWW-Authenticate: Token
X-Frame-Options: SAMEORIGIN

Request Headers
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Token ***703c1
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Host: etes.jrvarma.in
Origin: http://localhost:8000
Pragma: no-cache
Referer: http://localhost:8000/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by tasn** [comment]
Sorry, it was a stupid test, because we already assumed etesync sends it
correctly... Cab you check what headers apache forwards? Or better yet,
google about making sure apache forwards all of the headers? I don't know
apache that well, etesync is served by nginx.

**Comment by jrvarma** [comment]
Confirmed that `etesync` works fine when using the `django` development server running on a non privileged port. So this is an apache issue. Will search for ways to fix the apache problem.

**Comment by jrvarma** [comment]
Adding the line `WSGIPassAuthorization On` inside the `VirtualHost` configuration section ensures that `apache` forwards the `Authorization` header to `etesync`. Now it works with the `apache` web server.

If you would like to add the `apache` configuration instructions to the documentation, I can upload a redacted version of my `.conf` fle.

**Comment by jrvarma** [comment]
Adding the line 

    WSGIPassAuthorization On

inside the `VirtualHost` section of the `apache` configuration file solves the problem. 

The issue may be closed.

If you would like to add `apache` configuration instructions to the documentation, I can upload my configuration file.

**Comment by jrvarma** [comment]
Adding the line

     WSGIPassAuthorization On

to the `VirtualHost` section of the `apache` configuration file solves the problem.

Issue may be closed. If you want to add `apache` configuration instructions to the documentation, I can upload a redacted configuration file.

**Comment by tasn** [comment]
Sure thing. Open a PR and I'll happily include it. If you do this, I'll probably also take the time to upload my nginx config.
