### ISSUE TITLE
Support an external configuration file

### ISSUE THREAD

**Issue by mathstuf** [etesync/server-skeleton#8]
Maybe something simple like:

```python
try:
    from etesync_site_config import *
except ImportError:
    pass
```

at the end of `settings.py` would suffice. Then `PYTHONPATH` can be setup to have the module available and the settings override the default settings.

**Comment by tasn** [comment]
I'm closing this since you already sent a PR. :)

**Comment by mathstuf** [comment]
I usually let the PR close issues ,but OK :) .

**Comment by tasn** [comment]
I do too when it's a long lived issue. Though when there's immediately a PR with a fix, I'd rather just have a PR, no need for duplication. Though it really doesn't matter. :)

**Comment by victor-rds** [comment]
I have a docker image based on this repo, normally I just overwrote the `settings.py` with mine, but now with this feature I could add a new file instead of overwriting and this a much better solution! It enables use of volumes, swarm secrets and configs, and other benefits.

Sadly I know way little of python and failed miserably, can you update the documentation in how to use this feature?

**Comment by tasn** [comment]
It says so in the comment in the config file:

```
# Make an `etesync_site_settings` module available to override settings.
```

Though I understand it's probably not obvious to people who are not very proficient with Python. It essentially means you need to create a module that exports the wanted settings in the path. The easiest way to achieve that is to create a file called: `etesync_site_settings.py` and put it in the top source directory. That should be sufficient for your use with Docker.

I'd love to support your effort with making a docker image (and maybe even make it the official image if you're fine with that and it's in good enough shape). Please free to reach out to me by email if you'd like to chat more about it. It's my first name at etesync.com.

**Comment by victor-rds** [comment]
Thank you very much! 

> Though I understand it's probably not obvious to people who are not very proficient with Python. 

That was the key here :sweat_smile:, well that and `put it in the top source directory`, seriously my failures were only by this small detail! Based on other django examples I found here is what I tried:
- Added `etesync_site_settings.py` at same level of `settings.py`; no luck
- Added `etesync_site_settings` directory, with my custom `.py` file,  at same level of `settings.py`; no luck
- Added `etesync_site_settings` directory, with my custom `.py` file,  at same the top; no luck

I was so frustrated that made my own workaround `sed -i 's/etesync_site_settings/.docker/g' $BASE_DIR/etesync_server/settings.py` and added my `docker.py`, it works, but that wasn't an elegant solution, if all possible I don't want to mess with any of this repository files!

I'm rewriting from the scratch, as soon as I build to the hub I'll let you know!
Thanks once again, and sorry for my rusty english.

**Comment by tasn** [comment]
Ha, you were very close with this one:

> Added etesync_site_settings directory, with my custom .py file, at same the top; no luck

You can also create such a directory and then name the file __init__.py and it'd be the same as having a file called etesync_site_settings.py.

Please let me know if you have any more questions. Don't hesitate to ask!
